### PR TITLE
added devise

### PR DESCRIPTION
**Pull request by scionet**

### CODE REVIEW

**Comment by qiyundai** [comment]
Just noticing why we aren't getting a conflict yet -- The conflicts happen between the main and the branch a pull request is created for. We would need to merge one of them first to see a conflict, if that's what we want.

**Comment by qiyundai** [comment]
And to point out a different between Sam's version and mine, I deleted app/views/pages directory and created app/views/equipments and app/views/equipments/index.html.erb, and declared that to be the root path. I thought it makes sense since we aren't going to code a PagesController.

**Comment by scionet** [comment]
Yes, that makes sense on the page structure. We should merge your version and then we can see conflict in mine

**Comment by qiyundai** [comment]
Let's wait till Fred sees this?

**Comment by scionet** [comment]
agree.

**Comment by fredThem** [comment]
Ignore this, Just assigning everyone to attribute credits properly since we all worked on this. 
Thanks

**Pull request closed without merging**
